spring:
    security:
        user:
            name: admin
            password: 1234
    datasource:
        username: postgres
        url: jdbc:postgresql://localhost:5432/gira
        password: admin
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        show-sql: 'true'
    flyway:
        enabled: false
        driver-class-name: org.postgresql.Driver

server:
  port: 8088
java:
    runtime:
        version: 17
 