spring:
    security:
        user:
            name: admin
            password: 1234
    datasource:
        username: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        password: admin
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
    flyway:
        enabled: false
        driver-class-name: org.postgresql.Driver

server:
  port: 8088
# java:
#     runtime:
#         version: 17
 